FROM rust
VOLUME /.ssh/
ENV "ACCOUNTS_COUNT"="2" \
    "TRANSACTIONS_INTERVAL_SEC"="60" \
    "TRANSACTIONS_COUNT"="2" \
    "RETHINK_ENDPOINT"="142.93.137.28:28015" \
    "RETHINK_DATABASE"="blockchain" \
    "KAFKA_ENDPOINT"="142.93.137.28:9092" \
    "KAFKA_TOPIC"="requests" \
    "KAFKA_ACT_TIMEOUT"="1000" \
    "DISCORD_WEBHOOK"="" \
    "REPORTS_INTERVAL_SEC"="21600" \
    "FAIL_REPORTS_INTERVAL_SEC"="300"
CMD eval "$(ssh-agent -s)" && \
    ssh-add /.ssh/id_rsa && \
    git clone ssh://git@github.com/tonlabs/TON-SDK.git && \
    cd TON_SDK/monitoring-client && \
    cargo run